<?php

namespace Keogblem\FormTools;

use Illuminate\Support\ServiceProvider;

class FormToolsServiceProvider extends ServiceProvider
{
  public function boot()
  {
    logger("Keo Package");
  }

  public function register()
  {
    // parent::register(); // TODO: Change the autogenerated stub
  }

}
